[packages]
openssl = "*"
pkg-config = "*"

[phases.build]
cmds = ["cd backend && cargo build --release"]

[phases.start]
cmd = "cd backend && ./target/release/backend"

[variables]
RUST_VERSION = "1.70"