[build]
builder = "NIXPACKS"
buildCommand = "cd backend && cargo build --release"

[deploy]
startCommand = "cd backend && cargo run --release"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"

[variables]
PORT = "3001"