[build]
builder = "NIXPACKS"

[deploy]
startCommand = "cd backend && ./target/release/backend"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"

[variables]
PORT = "3001"